opencontainers/opencontainers.org

- assets/css/site.css
- config.toml
- layouts/partials/footer.html
> Add footer

- assets/css/site.css
- layouts/partials/footer.html
- layouts/partials/home/hero.html
- layouts/partials/home/trio.html
> Clean up CSS

- layouts/partials/footer.html
> Fix footer centering

- assets/css/site.css
- layouts/_default/list.html
- layouts/_default/single.html
- layouts/partials/footer.html
- layouts/partials/header.html
- layouts/partials/home/hero.html
- layouts/partials/home/trio.html
- layouts/partials/top-menu.html
- layouts/posts/single.html
> reorder tailwind classes

- config.toml
- content/about/leadership.md
- content/about/members.md
- content/about/oci-scope-table.md
- content/about/security-disclosure.md
- content/about/tob.md
Once again, making my life easier.
> Use config.toml for menus instead

- assets/css/styles.css
- config.toml
- content/blog/_index.md
- content/posts/_index.md
- content/posts/announcements/_index.md
- content/posts/announcements/index.md
- content/posts/blog/_index.md
- content/posts/news/_index.md
- content/posts/releases/_index.md
- content/releases/_index.md
- layouts/_default/list.html
- layouts/_default/section.html
- layouts/_default/single.html
- layouts/partials/feed-item.html
- layouts/partials/home/newsfeed.html
- layouts/partials/page-numbers.html
- layouts/partials/single-title.html
- layouts/posts/single.html
> [WIP] Create blog/news listing pages

- content/posts/news/2017-09-26-siliconangle-why-the-new-open-container-initiative-standard-is-a-milestone-for-software.md
- content/posts/news/2017-10-11-windows-itpro-using-containers-look-for-the-oci-seal-of-approval.md
- content/posts/news/2018-04-09-container-journal-oci-standardizes-container-registry-protocol.md
- content/posts/news/2018-04-10-sdxcentral-oci-standardizes-container-image-distribution-based-on-docker-registry.md
- content/posts/news/2018-04-10-zdnet-open-container-initiative-nails-down-container-image-distribution-standard.md
- content/posts/news/2018-04-11-the-new-stack-open-container-initiative-creates-a-distribution-specification-for-registries.md
- content/posts/news/2019-09-10-container-journal-oci-launches-artifacts-project-to-reduce-registries-required.md
> Convert remaining news stories

- content/posts/announcements/2018-03-14-oci-new-members.md
- content/posts/announcements/2018-04-09-oci-announces-dist-spec-project.md
- content/posts/announcements/2018-08-29-oci-welcomes-alibaba-cloud.md
> Migrate remaining announcements

- config.toml
> Disable sections

- config.toml
> Revert sections

- config.toml
> Use abs URLs in menus for testing

- layouts/_default/single.html
- layouts/partials/home/members.html
- layouts/posts/list.html
- layouts/shortcodes/card-container.html
- layouts/shortcodes/card.html
> Remove gap classes

- content/release-notices/overview.md
> Signed-off-by: Celeste Horgan <celeste@cncf.io>

- content/about/tob.md
> Let's just call this leadership

- config.toml
> Update leadership menu

- layouts/posts/single.html
> Add extra fields for press releases, news posts

- assets/css/site.css
- content/about/tob.md
- layouts/shortcodes/card.html
Explain in a bit more detail how the TOB is chosen, as well as what the
TOB Chair is. In addition, put the terms in a separate "subtitle"
section of each card.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> content: cleanup TOB information

- content/about/tob.md
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
> tob: add Jon Johnson's GitHub handle

- content/posts/blog/2020-08-03-umoci.md
> Add umoci blog post

- content/posts/blog/2020-10-30-consuming-public-content.md
Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>
> Typos, ordering of TOS references and other fixes

- content/posts/blog/2020-10-30-consuming-public-content.md
Incorporated feedback from Dan @ Codefresh, links from VMWare & Docker and other content edits
> Consuming Public Content updates

- content/about/tob.md
Signed-off-by: Phil Estes <estesp@gmail.com>
> Update Phil Estes bio

- content/community/overview.md
Also update communications (Slack, IRC, Matrix) and GitHub project links
Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>
> Update community page with proper call info

- layouts/_default/single.html
- layouts/posts/single.html
Fixes #68. 
Preview: https://deploy-preview-70--opencontainers.netlify.app/posts/blog/2020-10-30-consuming-public-content/
cc @caniszczyk
> Adjust padding on mobile resolutions

- content/posts/blog/2021-05-05-oci-dist-spec-v1.md
> Add blog on dist spec v1.0

- README.md
> Fix CLA ref

- content/posts/announcements/2021-05-04-oci-dist-spec-v1.md
> Move dist-spec blog to announcements

- content/release-notices/overview.md
- content/release-notices/v1-0-0-distribution-spec.md
> Add dist spec release notice

- content/posts/announcements/2021-05-04-oci-dist-spec-v1.md
> Fix date of OCI dist spec release

- content/release-notices/overview.md
> Add release notice for image spec 1.0.2

- content/release-notices/v1-0-2-image-spec.md
> Add image spec rel notice

- content/posts/blog/2021-12-06-oci-member-spotlight-chainguard.md
> Add Chainguard member spotlight

- content/posts/blog/2021-10-11-oci-summit.md
> Fix tweet reference

- layouts/partials/home/members.html
> Add Chainguard member logo

- layouts/partials/home/members.html
> Change to CG png logo

- netlify.toml
> Try another way to re-direct

- content/posts/blog/2022-01-31-oci-in-2022.md
> Add OCI TOB 2022 blog post

- config.toml
- content/about/overview.md
- content/faq.md
fixes https://github.com/opencontainers/opencontainers.org/issues/117
> Mention about distribution-spec

- content/community/overview.md
> Update OCI chat link

- content/community/overview.md
Signed-off-by: Brandon Mitchell <git@bmitch.net>
Fixes #116
> Fixing slack link

- content/posts/blog/2023-01-26-oci-in-2023.md
> Add OCI in 2023 blog post with TOB results

- content/posts/blog/2023-02-16-OCI-at-container-plumbing-conference.md
This is a draft to submit to opencontainers.org
> Added blog to advertise Container Pluming Days 2023

- netlify.toml
fixes: https://github.com/opencontainers/.github/issues/39
Can't seem to do it in the Netlify UI, so let's try the netlify.toml file
> Adding chat redirect

- content/about/tob.md
This brings the website in line with https://github.com/opencontainers/tob
cc @vbatts @jonjohnsonjr
> tob: update affiliations

- content/release-notices/overview.md
- content/release-notices/v1-2-0-runtime-spec.md
Updating member list, fixing a broken link
> Company and ded link fixing

- content/posts/blog/2024-02-19-oci-runtime-spec-v1-2.md
https://github.com/opencontainers/runtime-spec/releases/tag/v1.2.0
> blog: Add "OCI Runtime Spec v1.2"

- content/posts/blog/2024-02-18-oci-runtime-spec-v1-2.md
https://github.com/opencontainers/opencontainers.org/pull/150#issuecomment-1952750991
> Fix the date in the blog for OCI Runtime v1.2

- content/posts/blog/2024-03-13-image-and-distribution-1-1.md
Adding a blog post for the image and distribution spec 1.1.0 releases.
> Blog post for image and distribution 1.1.0

- content/release-notices/overview.md
> add missing parenthesis

- netlify.toml
Fix the governance redirect on netlify.
See: https://docs.netlify.com/routing/redirects/
> Fix governance redirect
